adds functions for setup to init command

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -1,8 +1,57 @@
 #!/usr/bin/env bash
-## Run blt setup commands to prepare your local site for
-## development.
+
+## Initialize stack, site requirements, and settings
 ##
 ## Usage: fin init
 
+# Abort if anything fails
+set -e
+#-------------------------- Settings --------------------------------
+
+# PROJECT_ROOT is passed from fin.
+# The following variables are configured in the '.env' file: DOCROOT, SITE_DIRECTORY, SOURCE_ALIAS and others.
+
+DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
+SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
+
+#-------------------------- END: Settings --------------------------------
+
+#-------------------------- Helper functions --------------------------------
+
+# Console colors
+red='\033[0;31m'
+green='\033[0;32m'
+green_bg='\033[42m'
+yellow='\033[1;33m'
+NC='\033[0m'
+
+echo-red () { echo -e "${red}$1${NC}"; }
+echo-green () { echo -e "${green}$1${NC}"; }
+echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
+echo-yellow () { echo -e "${yellow}$1${NC}"; }
+
+#-------------------------- END: Helper functions --------------------------------
+
+
+#-------------------------- Execution --------------------------------
+
+# Stack initialization
+echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
+fin project start
+
+echo -e ""
+echo -e "${green_bg} Step 2 ${NC}${green} Installing project requirements...${NC}"
+fin exec composer clear-cache
+fin exec COMPOSER_PROCESS_TIMEOUT=2000
+fin exec composer install
+
+# Site initialization
+echo -e ""
+echo -e "${green_bg} Step 3 ${NC}${green} Initializing site...${NC}"
+cd $DOCROOT_PATH
 fin blt blt:init:settings
-fin blt drupal:install
+
+echo -en "${green_bg} DONE! ${NC} "
+echo -e "${green}run ${yellow}fin init-site ${green} to initialize local site.${NC}"
+
+#-------------------------- END: Execution --------------------------------
